apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
  namespace: <namespace>
spec:
  params:
    - default: master
      description: The git revision (SHA)
      name: gitrevision
    - description: "The git repository url"
      name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
      spec:
        pipelineRef:
          name: <pipeline-name>
        serviceAccountName: pipeline
